LOAD DATA INFILE 'location.dat' INTO TABLE Location FIELDS TERMINATED BY '|*|';
LOAD DATA INFILE 'users.dat' INTO TABLE Users FIELDS TERMINATED BY '|*|';
LOAD DATA INFILE 'categories.dat' INTO TABLE Categories FIELDS TERMINATED BY '|*|';
LOAD DATA INFILE 'items.dat' INTO TABLE Items FIELDS TERMINATED BY '|*|';
LOAD DATA INFILE 'items_categories.dat' INTO TABLE Items_Categories FIELDS TERMINATED BY '|*|';
LOAD DATA INFILE 'bids.dat' INTO TABLE Bids FIELDS TERMINATED BY '|*|';
