LOAD DATA LOCAL INFILE 'dat/Locations.dat' INTO TABLE Location FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'dat/Users.dat' INTO TABLE Users FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'dat/Categories.dat' INTO TABLE Categories FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'dat/Items.dat' INTO TABLE Items FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'dat/ItemCategories.dat' INTO TABLE Items_Categories FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'dat/Bids.dat' INTO TABLE Bids FIELDS TERMINATED BY '|*|';
